### ISSUE TITLE
EVPN Support in L2NM: Split Horizon

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#202]
Based on RFC7432, Split Horizon filter should be supported in EVPN, it is referred to 
filtering mechanism on the PE node to prevent such loop and packet
duplication, e.g.,If a CE is multihomed to two or more PEs (represented by an ES
ES1) and operating in an All-Active redundancy mode, sends a BUM
(i.e., Broadcast, Unknown unicast, or Multicast) packet to one of
these PEs, then it is important to ensure the packet is not looped
back to the CE via another PE connected to this CE. 
We proposed to add the following parameter under vpn-node list
   leaf split-horizon {
         type boolean;
         default "false";
         description
             "When Split horizon is supported, the filtering mechanism on the VPN node 
		     should be enabled to prevent such loop and packet duplication";
        }

**Comment by oscargdd** [comment]
Comments:
1) it is related to a group
2) when related to multihoming, it is Mandatory, should not be an option.
In VPLSs,  it can be configured. However in E-VPN it is a must. 
3) Now, it is at vpn network access/connection level in L2NM. 
Please discuss more here or in the list

**Comment by sbarguil** [comment]
@oscargdd open the discussion on the list

**Comment by boucadair** [comment]
fixed in https://github.com/IETF-OPSAWG-WG/lxnm/commit/cadf6f481d1150a27cd9fb70d45f72821cab8434
