### ISSUE TITLE
EVPN Support in L2NM: Bridge Domain ID definition

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#203]
A bridge domain is a set of logical ports that share the same flooding or broadcast characteristics.
   Bridge domain can be supported by EVPN, in case of VXLAN, bridge domain ID can be set to VNID.
list vpn-node {
….
        leaf bd-id {
        type uint32 {
          range "1..16777215";
        }
        description
          "Bridge domain ID. A bridge domain is a set of 
		  logical ports that share the same flooding or broadcast characteristics.
		  It spans one or more ports of multiple devices.";
      }

**Comment by oscargdd** [comment]
prepare material for next call to understand the use case

**Comment by sbarguil** [comment]
Prepare material for next call to understand the use case. @billwuqin

**Comment by boucadair** [comment]
@billwuqin: closing as we don't have any update. Please reopen if you still think this is an issue to be fixed.
