### ISSUE TITLE
L2NM: multihoming: need fields for ESI, LACP System ID and LACP Administrative-key value

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/lxnm#219]
The L2NM has a method to indicate the multi-homing method used on a site-network-access (single-active or all-active). However, we need fields for the ESI, LACP System ID and LACP Administrative-key value, as they must have same value on the site-network-access of all PEs  that are attached to the same site.

**Comment by boucadair** [comment]
@julianL999, can you please check 764cd6a?

Thanks.

**Comment by julianL999** [comment]
> @julianL999, can you please check [764cd6a](https://github.com/IETF-OPSAWG-WG/lxnm/commit/764cd6a30f69acca6de8b590c73bf8a75e5ae23f)?
> 
> Thanks.

Thanks Med, this is great. Couple of comments, can we change "key" to "admin-key" as that is what it is normally called? In the ESI description under vpn-network-access, currently it says "vpn-network-access associated to the ESI." How about instead saying "ESI associated to this vpn-network-access"?

**Comment by oscargdd** [comment]
Agree with Julian, the ESI is associated to a particular vpn-network-access

**Comment by boucadair** [comment]
> 
> 
> Agree with Julian, the ESI is associated to a particular vpn-network-access

Sure. Please check 9356041.

More edits will be done once we have a stable version of the module.
