### ISSUE TITLE
L3NM: extend the scope and change name of ie-profiles to vpn-instance-profiles

### ISSUE THREAD

**Issue by p-sherratt** [IETF-OPSAWG-WG/lxnm#224]
We’re currently working on an internal implementation of a network controller using the latest draft of this model, and would like to propose some potential improvements to the representation of data which typically maps down to the concrete implementation of a routing instance:

[1] It's understood that the vpn-node is a currently a logical abstraction which blends both network element/device and routing instance details together. Because of this, there are a lot of attributes/leaves which may need to be duplicated for each routing instance of the VPN on each vpn-node.  There is some separate abstraction already of the `ie-profile` which reduces some of this duplication, and it is proposed here that all "routing instance" specific data may be better represented under a new `vpn-instance-profile` as outlined in the yang-tree mockup below.

[2] The vpn-instance-profile container maintains attributes common to a vpn's routing instance across multiple vpn-nodes.  It would attach via mandatory leafref to each `vpn-network-access`, and supersedes the concept of the node-ie-profile which attached to the vpn-node.  Hence, the `vpn-instance-profile` is still abstracted but it would typically map directly to the concrete implementation of a VRF routing instance on a PE device.

[3] Some attributes from the vpn-instance-profile may need to be overridden on a given vpn-node.  Therefore an `active-vpn-instance-profiles` list is added to the `vpn-node` to allow for representation of these local modifications, but also serves as an explicit list of vpn-instance-profiles which are available for attachment to vpn-network-accesses on the respective vpn-node.  Making this explicit provides a clear view of the routing instances which a vpn-node needs to support.

The final value of each of these routing instance attributes when mapping into the device domain would be coalesced from the following paths, where the first existing path's value is used.

- /l3vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/<attribute>
- /l3vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/active-vpn-instance-profiles/vpn-instance-profile{vpn-instance-profile-id}/<attribute>
- /l3vpn-ntw/vpn-services/vpn-service/vpn-instance-profiles/vpn-instance-profile{vpn-instance-profile-id}/<attribute>

vpn-instance-profile-id under the vpn-network-access is a leafref pointing to active-vpn-instance-profiles list under the vpn-node.

vpn-instance-profile-id under the active-vpn-instance-profiles is a leafref pointing to vpn-instance-profiles list under the vpn-service.

## Proposed structure mock-up

```
module: ietf-l3vpn-ntw
  +--rw l3vpn-ntw
     ...
     +--rw vpn-services
        +--rw vpn-service* [vpn-id]
           +--rw vpn-id                   vpn-id
           +--rw vpn-name?                string
           +--rw vpn-description?         string
           +--rw customer-name?           string
           +--rw parent-service-id?       vpn-common:vpn-id
           +--rw vpn-type?                identityref
           +--rw vpn-service-topology?    identityref
           ...
[1]        +--rw vpn-instance-profiles    (instead of ie-profiles)
           |  +--rw vpn-instance-profile* [vpn-instance-profile-id]
           |     +--rw vpn-instance-profile-id      string
           |     +--rw instance-role?                   (was: node-role)
           |     +--rw local-autonomous-system?       inet:as-number {vpn-common:rtg-bgp}?
           |     +--rw (rd-choice)?
           |     |  +--:(directly-assigned)
           |     |  |  +--rw rd?                  rt-types:route-distinguisher
           |     |  +--:(pool-assigned)
           |     |  |  +--rw rd-pool-name?        string
           |     |  |  +--ro rd-from-pool?        rt-types:route-distinguisher
           |     |  +--:(full-autoasigned)
           |     |  |  +--rw auto?                empty
           |     |  |  +--ro rd-auto?             rt-types:route-distinguisher
           |     |  +--:(no-rd)
           |     |     +--rw no-rd?               empty
           |     +--rw vpn-targets
           |     |  ...
           |     +--rw maximum-routes
           |     |  ...
           |     +--rw multicast {vpn-common:multicast}?
           |        ...
           +--rw vpn-nodes
              +--rw vpn-node* [vpn-node-id]
                 +--rw vpn-node-id                union
                 |  ...
                 +--rw local-autonomous-system?       inet:as-number {vpn-common:rtg-bgp}?
                 +--rw router-id?                     inet:ip-address
                 | ...
[3]              +--rw active-vpn-instance-profiles    [2]
                 |  +--rw vpn-instance-profile* [vpn-instance-profile-id]
                 |     +--rw vpn-instance-profile-id          -> ../../../vpn-instance-profile/vpn-instance-profile-id
                 |     +--rw local-autonomous-system?       inet:as-number {vpn-common:rtg-bgp}?
                 |     +--rw router-id?                     inet:ip-address
                 |     +--rw (rd-choice)?
                 |        ...
                 |  ...
                 +--rw vpn-network-accesses
                    +--rw vpn-network-access* [id]
                       +--rw id                         vpn-common:vpn-id
                       |  ...
[2]                    +--rw vpn-instance-profile-id      -> ../../active-vpn-instance-profiles/vpn-instance-profile/vpn-instance-profile-id
                       |  ...
```

## Example usage

Here is a mock-up of how the revised structure might be used to represent a hub-and-spoke topology built by a service orchestrator.

```
l3vpn-ntw vpn-services vpn-service VPN_1
  vpn-service-topology hub-spoke
  vpn-instance-profiles vpn-instance-profile HUB
    access-role hub-role
    traffic-protection enabled
    availability access-priority 100
    maximum-routes 100
    local-autonomous-system 64510
    rd 0:0:1001
    vpn-targets vpn-target 1
      route-target-type both
      route-targets 0:64510:1001
    !
    vpn-targets vpn-target 2
      router-target-type import
      route-targets 0:64510:1002
  !
  vpn-instance-profiles vpn-instance-profile SPOKE
    access-role spoke-role
    availability access-priority 90
    maximum-routes 1000
    local-autonomous-system 64510
    rd 0:0:1002
    vpn-targets vpn-target 1
      route-target-type import
      route-targets 0:64510:1001
    !
    vpn-targets vpn-target 2
      router-target-type both
      route-targets 0:64510:1002
  !
  !
  vpn-nodes vpn-node PE1
    ne-id pe1
    router-id 172.16.0.1
    active-vpn-instance-profiles vpn-instance-profile HUB
      availability access-priority 110
      maximum-routes 10
      rd 1:172.16.0.1:1001
    !
    vpn-network-accesses vpn-network-access xe-0/0/0.10000
      vpn-instance-profile-id HUB
      connection logical-interface peer-reference 10000
      ip-connection ipv4 static-addresses address 1
        provider-address 10.255.1.0
        customer-address 10.255.1.1
        prefix-length 31
    !
    vpn-network-accesses vpn-network-access xe-0/0/0.10001
      vpn-instance-profile-id SPOKE
      connection logical-interface peer-reference 10001
      ip-connection ipv4 static-addresses address 1
        provider-address 10.0.1.0
        customer-address 10.0.1.1
        prefix-length 31
  !
  vpn-nodes vpn-node PE2
    ne-id pe2
    router-id 172.16.0.2
    local-autonomous-system 64520
    active-vpn-instance-profiles vpn-instance-profile HUB
      rd 0:172.16.0.2:1002
    !
    active-vpn-instance-profiles vpn-instance-profile SPOKE
      maximum-routes 100
    !
    vpn-network-accesses vpn-network-access xe-0/0/0.10000
      vpn-instance-profile-id HUB
      connection logical-interface peer-reference 10000
      ip-connection ipv4 static-addresses address 1
        provider-address 10.255.2.0
        customer-address 10.255.2.1
        prefix-length 31
  !
  vpn-nodes vpn-node PE3
    ne-id pe3
    router-id 172.16.0.3
    active-vpn-instance-profiles vpn-instance-profile HUB
    active-vpn-instance-profiles vpn-instance-profile SPOKE
    vpn-network-accesses vpn-network-access xe-0/0/0.10000
      vpn-instance-profile-id SPOKE
      connection logical-interface peer-reference 10000
      ip-connection ipv4 static-addresses address 1
        provider-address 10.0.3.0
        customer-address 10.0.3.1
        prefix-length 31
!
```

**Comment by boucadair** [comment]
Hi Paul, 

Thank you for raising the comment. I do see a value in factorizing data. 

In order to assess the gain of restructuring (and identify which data node can be factorized), I wonder whether you made the exercise of mapping your intended configuration with the current module structure.

Did you encountered any particular issue?

Thank you.

**Comment by p-sherratt** [comment]
Hi Med,

We've found no particular issue so far in mapping L3NM to intended configuration.

The motivation for raising this was to simplify the mapping from L3SM of any of the vpn's routing instance details which can be factorised into a common profile (which often is all of them).

A less significant change to the model and draft document might be just to adjust the name & scope of ie-profile like this issue subject line suggests, but retain the current L3NM concept of an abstract vpn-node whereby "the network controller will decide how to split the 'vpn-node' into VRFs" :

```
        +--rw vpn-service* [vpn-id]
           | ...
           +--rw vpn-instance-profiles    (instead of ie-profiles)
           |  +--rw vpn-instance-profile* [vpn-instance-profile-id]
           |     +--rw vpn-instance-profile-id      string
           |     +--rw instance-role?                   (was: node-role)
           |     +--rw local-autonomous-system?       inet:as-number {vpn-common:rtg-bgp}?
           |     +--rw (rd-choice)?
           |     |  +--:(directly-assigned)
           |     |  |  +--rw rd?                  rt-types:route-distinguisher
           |     |  +--:(pool-assigned)
           |     |  |  +--rw rd-pool-name?        string
           |     |  |  +--ro rd-from-pool?        rt-types:route-distinguisher
           |     |  +--:(full-autoasigned)
           |     |  |  +--rw auto?                empty
           |     |  |  +--ro rd-auto?             rt-types:route-distinguisher
           |     |  +--:(no-rd)
           |     |     +--rw no-rd?               empty
           |     +--rw vpn-targets
           |     |  ...
           |     +--rw maximum-routes
           |     |  ...
           |     +--rw multicast {vpn-common:multicast}?
           |        ...
           +--rw vpn-nodes
              +--rw vpn-node* [vpn-node-id]
                 +--rw vpn-node-id                union
                 +--rw local-autonomous-system?       inet:as-number {vpn-common:rtg-bgp}?
                 +--rw router-id?                     inet:ip-address
                 +--rw vpn-instance-profile          -> ../../../vpn-instance-profile/vpn-instance-profile-id
                 |  ...
```

Also with this smaller change, maybe `vpn-node-profile` is a more apt name than `vpn-instance-profile`.


Thanks for considering this.

**Comment by boucadair** [comment]
> We've found no particular issue so far in mapping L3NM to intended configuration.

Glad to hear that. 

> Also with this smaller change, maybe `vpn-node-profile` is a more apt name than `vpn-instance-profile`.

I like more "instance" as it is called under both vpn-node and vpn-network-access levels. Also having the the list of active instances at the node allows to override parameters at the vpn-node level, if needed. 

A proposal to take into account your comment can be seen at https://github.com/IETF-OPSAWG-WG/l3nm/commit/1e711eac8c3ecfd9f9d45caa0e9dad4da8413536
