### ISSUE TITLE
Update draft to clarify the use of vpn-instance profile

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/lxnm#225]
(1) Update the ie-profile and add new text to explain how data can be compared by means of vpn-instance-profile
(2) Add a new example to illustrate the use vpn-instance profile (the example will be IPv6-only).  
(3) Update existing examples to align with the updated structure.

**Comment by p-sherratt** [comment]
Hi Med,

I've updated my example using the latest module and have some feedback from using this.

[vpn-instance-profiles-example.json.txt](https://github.com/IETF-OPSAWG-WG/lxnm/files/6213561/vpn-instance-profiles-example.json.txt)

### IPv6 static assignment

> Only prefix assignment is possible with nowhere to specify a static address except for the "primary" address.


### IPv4 static assignment

> Only address assignment is possible with nowhere to specify the prefix length?


### Add "rd-suffix" choices for automatic per- PE/instance RD assignment...

> This accommodates a common use-case where only the Assigned Number subfield is assigned from a pool, and a type 1 RD is used where the Administrator subfield is set to the router-id used by the PE or VRF instance.
> 
> I'd used RD 0:0:x in my example by using reserved AS 0 to achieve the same outcome but in a less precise way.
> 
> Choice cases `rd-suffix` and `rd-auto-suffix` are shown in the revised `rd-choice` cases below.


### Tidy up `rd-choice` cases

> This looks a bit messy because the case leafs do not have a clear prefix to disambiguate them from other attributes in the same container where the choices are attached to:

```
poc1(config-vpn-instance-profile-HUB)# ?
Possible completions:
  auto
  local-autonomous-system
  maximum-routes
  multicast
  no-rd
  rd
  rd-pool-name
  role
  vpn-targets
```

Revised `rd-choice` below:

```
           +--rw vpn-nodes
              +--rw vpn-node* [vpn-node-id]
                 +--rw vpn-node-id                     union
                 +     ...
                 +--rw active-vpn-instance-profiles
                    +--rw vpn-instance-profile* [profile-id]
                       +--rw profile-id                 -> /l3vpn-ntw/vpn-services/vpn-service/vpn-instance-profiles/vpn-instance-profile/profile-id
                       +--rw router-id?                 inet:ip-address
                       +--rw local-autonomous-system?   inet:as-number {vpn-common:rtg-bgp}?
                       +--rw (rd-choice)?
                       |  +--:(directly-assigned)
                       |  |  +--rw rd?                  rt-types:route-distinguisher
                       |  +--:(directly-assigned-suffix)
                       |  |  +--rw rd-suffix?           uint16
                       |  +--:(auto-assigned)
                       |  |  +--rw rd-auto
                       |  |  |  +--rw (rd-auto-choice)?
                       |  |  |     +--:(autonomous)
                       |  |  |     |  +--rw autonomous? none
                       |  |  |     +--:(from-pool)
                       |  |  |     |  +--rw from-pool?  string
                       |  +--:(auto-assigned-suffix)
                       |  |  +--rw rd-auto-suffix
                       |  |  |  +--rw (rd-auto-choice)?
                       |  |  |     +--:(autonomous)
                       |  |  |     |  +--rw autonomous? none
                       |  |  |     +--:(from-pool)
                       |  |  |     |  +--rw from-pool?  string
                       |  +--:(no-rd)?
                       |     +--rw rd-none?             empty
                       +--ro operational-rd?            rt-types:route-distinguisher
```
> Note that the `rd-from-pool` is moved into a separate `operational-rd` attribute which would only be available at the active vpn-instance-profile level, and this could be accessed to also retrieve the RD for rd-suffix and rd-auto-suffix cases, or simply return the directly assigned RD.

### Per-address-family vpn-targets

> I wonder if there may be a need for per-address-family vpn-targets, and if address-family specific details would be better grouped together?
> 
> If we were to refactor the maximum-routes selector for this purpose it may look like:

```
                       ...
                       +--rw address-family
                          +--rw selector* [address-family protocol]
                             +--rw address-family    identityref
                             +--rw protocol          identityref
                             +--rw vpn-targets
                             |  +--rw vpn-target* [id]
                             |  |  +--rw id                   int8
                             |  |  +--rw route-targets* [route-target]
                             |  |  |  +--rw route-target    rt-types:route-target
                             |  |  +--rw route-target-type    rt-types:route-target-type
                             |  +--rw vpn-policies
                             |     +--rw import-policy?   string
                             |     +--rw export-policy?   string
                             +--rw maximum-routes
```

Cheers,

Paul

**Comment by p-sherratt** [comment]
Thanks for these updates.  Regarding the changes for static address assignment please see: https://github.com/IETF-OPSAWG-WG/lxnm/commit/1530b8f404eea0cdf7a4de16455a043aabd7b4b4#commitcomment-49398169
