### ISSUE TITLE
PM Scope (Adrian Farrel's comments from WG adoption)

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/lxnm#230]
From Adrian Farrel:

`It is unclear to me from Section 1 whether this document is intended to be limited to L3VPNs or applies to all VPNs. The very first sentence gives a strong hint that the scope is restricted to L3VPN, but I think that is not the intention.`

**Comment by lana-wu** [comment]
Update the first paragraph in section 1 with the following one:
   [RFC8969] describes a general framework for automating service and
   network management with YANG model, proposing the performance
   measurement telemetry model can tie with service, such as Layer 3 VPN
   and Layer 2 VPN, or network models to monitor network performance or
   Service Level Agreements (SLA).
