### ISSUE TITLE
Add a ref to 8309 (Adrian Farrel's comments from WG adoption)

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/lxnm#231]
From Adrian Farrel:

`Maybe Figure 1 should be set in the context of RFC 8309. In particular, s/Service Network Models/Network Service Models/ But it might also be nice to include a reference to 8309 to help give meaning to the figure`

**Comment by lana-wu** [comment]
Added text as follows:
As shown in Figure 1, in the context of layering model architecture
   described in [RFC8309], the network and VPN service performance
   monitoring (PM) model can be used to expose some performance
   information to the above layer.
                             +---------------+
                             |   Customer    |
                             +---------------+
             Customer Service Models |
                                     |
                             +-----------------+
                             |    Service      |
                             |  Orchestration  |
                             +-----------------+
             Network Service Models | | Network and VPN Service PM Model
                                    | |
                             +-----------------+
                             |     Network     |
                             |   Controller    |
                             +-------|----------+
                                     |
             +------------------------------------------------+
                                   Network
