### ISSUE TITLE
Add examples to clarify multi-domain scenarios

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#232]
*Open on:* Apr 30, 2020
*Comes* from: https://github.com/IETF-OPSAWG-WG/l2nm/issues/11

In the last OPSAWG meeting there ware the following comments can hierarchical
VPN be supported in this SM? Oscar: Yes, but more review is needed to see if it
is fully supportable Zhenbin Li: Inter-AS scenario?

The proposal is to add examples in the draft to explain the usage in both scenarios.

---

*Lastest comments by @oscargdd*

examples sent by roque, upload to git and review text and formatting to be provided

**Comment by boucadair** [comment]
Added a placeholder to the draft to list all examples. We need more to be included, not only multi-domain ones

**Comment by boucadair** [comment]
Covered in #313
