### ISSUE TITLE
EVPN: Add support for dot1q push/pop/translate options

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#236]
*Opened on*: Nov 12, 2020
*Comes from:* https://github.com/IETF-OPSAWG-WG/l2nm/issues/22

Missing the option to re-write dot1q information received in access.

---
*Latest comment:* by @Qin and @oscargdd :

- Should we see this as network level parameter or device level configuration parameters? Can we generate these parameters in the device level model during YANG to YANG translation?

- Let's keep the issue open, see the use case, and if needed, align and reuse from ccamp.

**Comment by rgaglian** [comment]
Attached a proposal on how to address this issues.

The translation process will be different depending on the intent behavior.

r.  


grouping subinterface-rewrite-common-grouping {
    container ingress {
      description "Set the tag rewriting policy for this EFP";
      presence "true";
      choice tag-choice {
        leaf pop {
          description "Remove one or more tags";
          when "../../../../../encapsulation-type = 'vpn-common:dot1q'";
          type enumeration {
            enum "1" ;
            enum "2";
          }
          mandatory true;
        }
        leaf push {
          description "Push one or more tags";
          type empty;
          mandatory true;
        }
        leaf translate {
          description "Replace tags with other tags";
          type enumeration {
            enum "1-to-1";
            enum "1-to-2";
            enum "2-to-1";
            enum "2-to-2";
          }
          mandatory true;
        }
      }
      must "pop!='' or push or translate!=''" {
        error-message "Please provide at least one of the tag-choices: pop, push or translate.";
      }

      leaf dot1q {
        description "<1-4094> - Push a Dot1Q tag";
        when "not(../pop)";
        mandatory true;
        type uint16 ;
      }

      leaf mode {
        type enumeration {
          enum symmetric;
        }
      }
    }
  }

  augment /l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-network-accesses/vpn-network-access/connection/dot1q-interface/dot1q {
    container rewrite {
      description "Tag Rewrite";
      presence "true";
      when "../c-vlan-id";
      uses subinterface-rewrite-common-grouping;
    }
  }


  augment /l2vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-network-accesses/vpn-network-access/connection/untagged-interface/untagged {
        container rewrite {
          tailf:info "Tag Rewrite";
          description "Tag Rewrite";
          presence "true";
          when "../sub-if-id";
          uses subinterface-rewrite-common-grouping;
        }
        description
          "Untagged";
      }

**Comment by sbarguil** [comment]
solved in #302
