### ISSUE TITLE
t-ldp with static label

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#237]
*Opened on*: Nov 12, 2020
*Comes from:* https://github.com/IETF-OPSAWG-WG/l2nm/issues/23

When using t-ldp as type, we are missing the mpls-label in the ac-pw-list.

---
*Latest comment:* by @oscargdd :

The question is if the need is to set up the label, and if so, would it be ok to do the same as in the case of RT/RD (auto asign vs explicit assign)

**Comment by rgaglian** [comment]
The title is wrong as this is not EVPN issue.

Propossed addition:

container t-ldp-pwe {
  list ac-pw-list {
    leaf mpls-label {
                        tailf:info "<16-1048575> - MPLS Label";
                        description "<16-1048575> - MPLS Label";
                        type uint32 {
                          range "16..1048575";
                        }
                      }
                 }
          }

**Comment by oscargdd** [comment]
The configuration of the MPLS label is out of the scope of the L2NM model. It would appy to a network creation phase. Plase Roque, check, and if you believe the use cases justifies the inclusion of it, reopen the issue.
