### ISSUE TITLE
EVPN: Missing validation for dot1q

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#238]
*Opened on*: Nov 12, 2020
*Comes from:* https://github.com/IETF-OPSAWG-WG/l2nm/issues/25

The following MUST statements are missing.

r.

  deviation "/l2vpn-ntw:l2vpn-ntw/l2vpn-ntw:vpn-services/l2vpn-ntw:vpn-service/l2vpn-ntw:vpn-nodes/l2vpn-ntw:vpn-node/l2vpn-ntw:vpn-network-accesses/l2vpn-ntw:vpn-network-access/l2vpn-ntw:connection/l2vpn-ntw:dot1q-interface/l2vpn-ntw:dot1q/l2vpn-ntw:c-vlan-id" {
    deviate add {
      must "../../../l2vpn-ntw:encapsulation-type='vpn-common:dot1q'"{
        error-message "c-vlan-id can only be set when encapsulation-type is 'vpn-common:dot1q'";
      }
  deviation "/l2vpn-ntw:l2vpn-ntw/l2vpn-ntw:vpn-services/l2vpn-ntw:vpn-service/l2vpn-ntw:vpn-nodes/l2vpn-ntw:vpn-node/l2vpn-ntw:vpn-network-accesses/l2vpn-ntw:vpn-network-access/l2vpn-ntw:connection/l2vpn-ntw:dot1q-interface/l2vpn-ntw:dot1q" {
    deviate add {
      must "../../l2vpn-ntw:encapsulation-type='vpn-common:dot1q' and l2vpn-ntw:c-vlan-id"{
        error-message "c-vlan-id is required when encapsulation-type is 'vpn-common:dot1q'";
      }

---
*Latest comment:* by @oscargdd :

ok, it is reasonable to add it. Qin can take care of creating a pr with the change

**Comment by boucadair** [comment]
@sbarguil: I'm not sure this isssue is still valid given the restructure made to the connection. Can you please check? 
Thanks.

**Comment by boucadair** [comment]
We do have the following check in the module

```
                      when "derived-from-or-self(../type, "
                         + "'vpn-common:dot1q')" {
                        description
                          "Only applies when the type of the
                           tagged interface is 'dot1q'.";
                      }
```
