### ISSUE TITLE
Node list: Limit elements for Point-to-point services

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#239]
*Opened on*: Nov 12, 2020
*Comes from:* https://github.com/IETF-OPSAWG-WG/l2nm/issues/26

In point-to-point services, there should be a max of 2 nodes defined in the node list.

---
*Latest comment:* by @Qin and @oscargdd :

Have a second thought, I am not sure we should add limit to the elements for point to point service.
There are multiple cases we can consider:

 - One PE connect to two ports, the the max-elements and min-elements can be set to 1
- Two PEs connect to each other with each having one port, the max-elements and min-elements can be set to 2
- Two local PEs are multihomed connecting the same remote PE, each PE having one port, the max-elements and min-elements can be set to 3
- Two local PEs are dualhomed connecting to two remote PEs in full mesh, two remote PEs are also dual homed, in this case, ,the max-elements and min-elements can be set to 4

Even for point to point there could be cases with more that two nodes, hence it is better to avoid the "artificial" limit. Roque, please check if you agree and we can close the issue.

**Comment by oscargdd** [comment]
In my view, I see that the use cases commented by samier, with dual homed PEs to provide point-to-point services justify that there are alternatives that make it difficult to establish the artificial limit.
