### ISSUE TITLE
how precedence-type is different from access-priority under availability

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#243]
*Opened on*: Feb 17, 2020
*Comes from:* https://github.com/IETF-OPSAWG-WG/l2nm/issues/5

I feel the role of access-priority and precedence-type is almost same. what is the their key difference? one is service level, the other is access level? Can you provide a usage example of precedence-type?

---
*Latest comment:* by @boucadair :

Please find an update to the common module at: IETF-OPSAWG-WG/lxnm@a8db4bf

**Comment by boucadair** [comment]
This issues is a subcase of #286
