### ISSUE TITLE
Align terminology in VPN PM draft and LxNM drafts

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/lxnm#244]
The terminology used in the VPN PM draft is different that in LxNM drafts. Hence, it would be requiered to align names and terms. Specially, the definition of a VPN and how it is composed.

**Comment by lana-wu** [comment]
Update the draft with VPN common YANG terms as follows:
module: ietf-network-vpn-pm
  augment /nw:networks/nw:network/nw:network-types:
    +--rw service-type!
       +--rw service-type?   identityref
  augment /nw:networks/nw:network:
    +--rw vpn-pm-attributes
       +--rw vpn-id?                 vpn-common:vpn-id
       +--rw vpn-service-topology?   identityref
  augment /nw:networks/nw:network/nw:node:
    +--rw pm-attributes
       +--rw node-type?                identityref
       +--rw role?                     identityref
       +--ro vpn-summary-statistics
          +--ro ipv4
          |  +--ro maximum-routes?        uint32
          |  +--ro total-active-routes?   uint32
          +--ro ipv6
          |  +--ro maximum-routes?        uint32
          |  +--ro total-active-routes?   uint32
          +--ro mac-num
             +--ro mac-num-limit?          uint32
             +--ro total-active-mac-num?   uint32
