### ISSUE TITLE
No difference between encapsulation-type and eth-inf-type

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#256]
In L2NM model,  encapsulation-type and eth-inf-type are two  parameter under connection, however both encapsulation-type and eth-inf-type use the same vpn-common:encapsulation-type as follows:
                container connection {
                  leaf encapsulation-type {
                    type identityref {
                      base vpn-common:encapsulation-type;
                    }
                    description
                      "Encapsulation Type";
                  }
                  leaf-list eth-inf-type {
                    type identityref {
                      base vpn-common:encapsulation-type;
                    }
                    description
                      "Ethernet Interface Type";
                  }

Quoted from RFC8466,
  identity eth-inf-type {
    description
      "Identity of the Ethernet interface type.";
  }

  identity tagged {
    base eth-inf-type;
    description
      "Identity of the tagged interface type.";
  }

  identity untagged {
    base eth-inf-type;
    description
      "Identity of the untagged interface type.";
  }
Something is wrong here.

**Comment by sbarguil** [comment]
solved in #302
