### ISSUE TITLE
why vxlan interface is under dot1q interface?

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#257]
In L2NM model, VXLAN interface is under dot1q interface
                       |  +--rw dot1q-interface
                       |  |  +--rw l2-access-type?   identityref
                       |  |  +--rw dot1q {vpn-common:dot1q}?
                       |  |  |  +--rw physical-inf?   string
                       |  |  |  +--rw c-vlan-id?      uint32
                       |  |  +--rw qinq {vpn-common:qinq}?
                       |  |  |  +--rw s-vlan-id?   uint32
                       |  |  |  +--rw c-vlan-id?   uint32
                       |  |  +--rw qinany {vpn-common:qinany}?
                       |  |  |  +--rw s-vlan-id?   uint32
                       |  |  +--rw vxlan {vxlan}?
                       |  |     +--rw vni-id?      uint32
                       |  |     +--rw peer-mode?   identityref
                       |  |     +--rw peer-list* [peer-ip]
                       |  |        +--rw peer-ip    inet:ip-address
The question, why VXLAN interface is not in the level as dot1q interface?

**Comment by boucadair** [comment]
Renamed the container.
