### ISSUE TITLE
Usage of cvlan-id-to-svc-map, t-ldp-pwe、l2tp-pwe

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#258]
Lack explanation on how to use cvlan-id-to-svc-map, t-ldp-pwe、l2tp-pwe?

**Comment by boucadair** [comment]
IMO, cvlan-id-to-svc-map should be removed as it only points to the current vpn-id. 

t-ldp-pwe and l2tp-pwe (to be renamed to ldp and l2tp) groups required data nodes when L2TP or LDP are used for signaling. We do have the following in the I-D:

```
   't-ldp-pwe':  Refers to LDP-signaled Pseudowires [RFC6074].

   'l2tp-pwe':  Refers to L2TP-signaled Pseudowires [RFC6074].
```

**Comment by boucadair** [comment]
cvlan-id-to-svc-map removed and t-ldp-pwe/l2tp-pwe clarified.
