### ISSUE TITLE
group-color clarification

### ISSUE THREAD

**Issue by billwuqin** [IETF-OPSAWG-WG/lxnm#259]
how to use group color? How group color is related to split horizon/group name?

**Comment by sbarguil** [comment]
The `split-horizon/group-name` should be the same across the VPN Network-access that belongs to the same session:

````

                    +--rw vpn-network-accesses
                       +--rw vpn-network-access* [id]
                       |  +--rw id                  vpn-common:vpn-id
                       |  +--rw description?        string
                       |  +--rw split-horizon
                       |     +--rw group-name?   string
````

In this moment  the `group-name` is a string.  However, it could be a reference if you want to make it clear.

**Comment by billwuqin** [comment]
Group color is defined under access-diversity/groups, are you proposing we should link group-color under access-diversity/groups with group-name under split-horizon? 
My question is whether group-color can be reused to represent group-name under split horizon? or this issue is related to #283? which consolidate split-horizon with access-diversity/groups parameters.

**Comment by billwuqin** [comment]
If the answer is it is related to #283 , I think it can be closed, if it is not, we could make it clear group-color as generic parameter doesn't cover split horizon usage which is defined under connection. Maybe I miss something.
