### ISSUE TITLE
Review from transport area of vpn-common

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/lxnm#262]
Here is a copy paste of the review by transport area review team

Reviewer: Wesley Eddy
Review result: Almost Ready

This document has been reviewed as part of the transport area review team's ongoing effort to review key IETF documents. These comments were written primarily for the transport area directors, but are copied to the document's authors and WG to allow them to address any issues raised and also to the IETF discussion list for information.

When done at the time of IETF Last Call, the authors should consider this review as part of the last-call comments they receive. Please always CC tsv-art@ietf.org if you reply to or forward this review.

(1) I noticed in the "qos-classification-policy" there is "l4" support either TCP or UDP.  It isn't clear if other transport protocols are purposefully not included.  Should this also support SCTP and/or DCCP, or other transport protocol numbers in general?  Are the QUIC aspects that might be matched contained within the UDP fields supported?

(2) Is the allowable MTU another aspect of VPN services that should be able to be expressed?

(3) ICMP isn't mentioned as an identity type, and I wondered if this should be.

**Comment by boucadair** [comment]
See https://mailarchive.ietf.org/arch/msg/opsawg/yrTTmQbclNTee1FIUGls2UmRBFk/
