### ISSUE TITLE
Review by Dhruv in Last call

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/lxnm#263]
Copy paste of Dhruv's review from LAST CALL

==
General:
- I guess the best practice for a section in the reference is "RFC
YYYY: The title, Section X" instead of "Section X of RFC YYYY"
[[[Med: Fixed here 961376c]]]
- Both YANG modules could use more references (Example multicast part in L2NM) 
[[[Med: Added mutlicast references here 961376c]]]
- ==
draft-ietf-opsawg-vpn-common:
- Not sure about the difference between the identity "sr-mpls" and "sr-te".
- Is there a reference for QinAny? Also, should we use 'QinQ' and 'QinAny' in the description, instead of 'qinq' and 'qinany'?
- Some of the references used in YANG are not listed in Section 9.
Example - IEEE Std 802.1Q, RFC 8453.
==
draft-ietf-opsawg-l3sm-l3nm:
- For leaf vpn-type, should we check that it is set to L3VPN in the YANG?
- For identity provider-dhcp-slaac, should we add if-feature vpn-common:ipv6.
[[[Med: Fixed here: 82cd4da]]
- typedef area-address is not used, yang:dotted-quad is used for isis which i think is incorrect. I suggest to use isis:area-address for ISIS and ospf:area-id-type for OSPF for the respective YANG modules.
- Why is the vpn-node-id a union for string or uint32? This is not done for any other identifier, only vpn-node-id...
[[[Med: Fixed here 8afb73f]]]
- leaf key for BGP
(/l3vpn-ntw/vpn-services/vpn-service/vpn-nodes/vpn-node/vpn-network-accesses/vpn-network-accesse/routing-protocols/routing-protocol/bgp/security/keying-material/key)
has an incorrect description as - "OSPF authentication key."
[[[Med: Fixed here: 415b123]]
- Maybe the keying-material should be under NACM?
- s/nontrollers/controllers/g
[[[Med: Fixed here a2559b3]]]
==

**Comment by oscargdd** [comment]
Remaining comments to address:

1) guess the best practice for a section in the reference is "RFC
YYYY: The title, Section X" instead of "Section X of RFC YYYY"
2) Both YANG modules could use more references:  Pending to do in L3NM
3) For leaf vpn-type, should we check that it is set to L3VPN in the YANG?
4) typedef area-address is not used, yang:dotted-quad is used for isis which i think is incorrect. I suggest to use isis:area-address for ISIS and ospf:area-id-type for OSPF for the respective YANG modules.
5) Why is the vpn-node-id a union for string or uint32? This is not done for any other identifier, only vpn-node-id...
leaf key for BGP

**Comment by oscargdd** [comment]
For 3, we think it is risky to restrict the type to L3 VPNs. There are other types of L3 based services that are not covered now. The identify for L3VPN covers VPNs as specified in RFC 4364. The VPNs beyond that scope will need a different type. Future augmenations can cover those cases. One example is L3 based EVPNs.  

Action point: add clarifying text in the L3NM draft

**Comment by oscargdd** [comment]
`typedef area-address is not used:` It can be deleted

yang:dotted-quad is used for isis which i think is incorrect. I suggest to use isis:area-address for ISIS and ospf:area-id-type for OSPF for the respective YANG modules. We are aligned with the types needed and used by isis:area-address for ISIS and ospf:area-id-type for OPSF

For example, the ospf yang model (https://tools.ietf.org/html/draft-ietf-ospf-yang-29
) defines:
 typedef area-id-type {
       type yang:dotted-quad;
       description
         "Area ID type.";
     }

So.. the result is the same and we avoid having to import the two yang models.

**Comment by boucadair** [comment]
> Why is the vpn-node-id a union for string or uint32? This is not done for any other identifier, only vpn-node-id...

I agree. We don't need to import implementation-specific concerns into the module. I suggest to change the type to: vpn-common:vpn-id;

**Comment by boucadair** [comment]
> `typedef area-address is not used:` It can be deleted

Done in 94b6627.

**Comment by boucadair** [comment]
>     * Maybe the keying-material should be under NACM?

We are trying to align with device modes to ease network-device mapping; hence the current choice in the draft.

**Comment by dhruvdhody** [comment]
> > ```
> > * Maybe the keying-material should be under NACM?
> > ```
> 
> 
> We are trying to align with device modes to ease network-device mapping; hence the current choice in the draft.

Not sure what is the best practice here! I see some device models like ietf-key-chain using nacm when it comes to sensitive data like keys while some don't.

**Comment by dhruvdhody** [comment]
> `typedef area-address is not used:` It can be deleted
> 
> yang:dotted-quad is used for isis which i think is incorrect. I suggest to use isis:area-address for ISIS and ospf:area-id-type for OSPF for the respective YANG modules. We are aligned with the types needed and used by isis:area-address for ISIS and ospf:area-id-type for OPSF
> 
> For example, the ospf yang model (https://tools.ietf.org/html/draft-ietf-ospf-yang-29
> ) defines:
> typedef area-id-type {
> type yang:dotted-quad;
> description
> "Area ID type.";
> }
> 
> So.. the result is the same and we avoid having to import the two yang models.

For the container ISIS, the area-address as yang:dotted-quad would be at odds with ISIS area format, which is -> 

     typedef area-address {
       type string {
         pattern '[0-9A-Fa-f]{2}(\.[0-9A-Fa-f]{4}){0,6}';
       }
       description
         "This type defines the area address format.";
     }
 
whereas dotted-quad is

     typedef dotted-quad {
       type string {
         pattern
           '(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}'
         + '([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])';
       }
       description
         "An unsigned 32-bit number expressed in the dotted-quad
          notation, i.e., four octets written as decimal numbers
          and separated with the '.' (full stop) character.";
     }

You cannot use ospf area-id format for ISIS

**Comment by boucadair** [comment]
> For the container ISIS, the area-address as yang:dotted-quad would be at odds with ISIS area format,

You are right. Fixed at: 7dd2193
