### ISSUE TITLE
L3NM: Adding leaf for vlan virtual interface id

### ISSUE THREAD

**Issue by rgaglian** [IETF-OPSAWG-WG/lxnm#266]
For same vendors, defining the cvlan-id is not "enough" to identify the target infrastructure. One example is Cisco IOS where you need the cvlan-id but also the BDI id to perform the configuration. Implementations are not force to do cvlan-id=BDI_id

I propose a new leaf:

          leaf cvlan-id {
            type uint16;
          }
          leaf cvlan-virtual-interface-id {
            description "cvlan virtual interface id, which could be different from the cvlan value";
            type uint16;
          }

**Comment by p-sherratt** [comment]
this might be abstracted better as a logical "service-reference" to the L2 service termination point, which could represent this BDI id/instance, or be mapped downstream via the domain orchestrator onto a BDI id or even multiple device-specific attributes.  For example in IOS you might have a different bridge-domain id to the service instance ID.

```
                       +--rw connection
                       |  +--rw logical-interface
                       |  |  +--rw peer-reference?   uint32
                       |  |  +--rw service-reference?  vpn-common:vpn-id
```

**Comment by boucadair** [comment]
Agree with Paul.

**Comment by rgaglian** [comment]
Fine with the alternative.

**Comment by rgaglian** [comment]
Before you close, would it be good to add a text in the description of the "service-reference" a mention to this possible use of that leaf?

**Comment by boucadair** [comment]
@rgaglian, can you please indicate which  modification to make to bc2919b

**Comment by oscargdd** [comment]
text and modification is OK. The issue can be closed
