### ISSUE TITLE
L3NM: Missing BGP update source for BGP clients

### ISSUE THREAD

**Issue by rgaglian** [IETF-OPSAWG-WG/lxnm#268]
I believe we need a way to signal what is the source interface for BGP sessions against the CPE.

Roque

Proposed changes:

 	container bgp {
          container update-source {
            presence "true";
            description "Source of routing updates";
            leaf if-type {
              description "Interface Type";
	     type string;
              mandatory true;
            }

            leaf if-id {
              description "Interface Id";
              type string;
              mandatory true;
            }

            leaf sub-if-id {
              description "Sub Interface Id";
              type int32;
            }
          }

**Comment by segevere** [comment]
what is the motivation of defining the BGP source, is it replace the neighbor ?

**Comment by rgaglian** [comment]
no, this is the source interface in the PE towards the CPE. The main example are neighbors running multi-hop where you may have many possible source IP interfaces. You need to set the source IP interface to make sure that the BGP TCP session always goes UP and does not depends on routing.
