### ISSUE TITLE
L3NM: revised modelling of vpn-network-access/connection parameters

### ISSUE THREAD

**Issue by p-sherratt** [IETF-OPSAWG-WG/lxnm#280]
Following on from #266 I had some more thoughts on the modelling of vpn-network-access/connection;

- The issue in needing the additional interface ID is an implementation-specific one which may be catered for in a domain orchestrator, however it may still be beneficial to track details like this for coordination in the L3NM.

- An irb/bridge-domain interface is a logical L3 interface that should be referenced in the `ip-connection` container instead of `connection`.  But an additional `bridge-reference` would also be beneficial for attaching the irb to.

- The terms `logical-interface` and `tagged-interface` in L3NM might be confusing, because these tagged interfaces are usually implemented by a device as a logical interface type, too.

So can I propose that we try for clear separation of concerns for:
  1. lower-layer encapsulation or tunnelling, always to be specified in the `connection` container
  2. L3 interface/service termination, always in the `ip-connection` container

Hence there would simply be a `port-id` reference in both containers:

```
                 +--rw vpn-network-accesses
                    +--rw vpn-network-access* [id]
                       +--rw id                         vpn-common:vpn-id
                       +  ...
                       +--rw connection
                       |  +--rw port-id?                   vpn-common:vpn-id
                       |  ...
                       +--rw ip-connection
                          +--rw port-id?                   vpn-common:vpn-id
                          ...
```

- `ip-connection/port-id` may refer to e.g. a loopback or irb interface type.  Depending on the vpn-node vendor implementation, it may also be the same interface type as used for encapsulation such as a tagged dot1q or qinq interface.  In the latter case, we would only need to reference the port-id once under the `connection` container.

Also consider the changes below:

```
                       +--rw connection
                       |  +--rw port-id?                   vpn-common:vpn-id   (from above)
[1]                    |  +--rw bridge-reference?          vpn-common:vpn-id
[2]                    |  +--rw l2vpn-id?                  vpn-common:vpn-id
                       |  |  ...
[3]                    |  +--rw encapsulation              # was: tagged-interface
                       |  |  ...
                       |  +--rw transport          # new container
                       |  |  +--rw type?           # new identityref  {pseudowire, vpls, vxlan}
                       |  |  +--rw pseudowire      # moved from bearer
                       |  |  ...
                       |  |  +--rw vpls            # moved from bearer
                       |  |  ...
[4]                    |  |  +--rw vxlan {vpn-common:vxlan}?   # moved from tagged-interface
                       |  |  ...
                   8< - - - -
[5]                    |  +--rw logical-interface      # remove this
[6]                    |  +--rw encapsulation-type     # remove this
                       |  |  ...
```

- [1] A bridge-reference is added to accommodate implementations where internal bridging is required.  For example, for irb interface connectivity where L2 encapsulation is not supported natively on the L3 interface.  It's assumed only a single common bridge may be needed for different connection scenarios.

- [2] **integrated L2/L3 vpn services** - For L2 and L3 vpn-services integrated on the same vpn-node, we may be able to specify the `ip-connection/port-id` irb interface and a common `connection/bridge-reference` local to the vpn-node.  If this reference is not useful to normal L2VPN provisioning it would be need to be added only in L3NM, and we can instead just add a reference to the `l2vpn-id` to ensure the layer-2 vpn-node configuration has been provisioned there first.

- [3] **tagged-interface** - This is renamed to `encapsulation`.  The available encapsulation types are: untagged, priority, dot1q, qinq.

- [4] **vxlan tunnelling** - From L3 termination perspective, the vxlan connectivity is similar to pseudowire headend connectivity which is currently described under the `bearer` container.  Both of these are really used for transport to a L2 services vpn-node so are moved to a new `transport` container.  Any specified `encapsulation` is stacked or signalled with the specified `transport`.

- [5] **logical-interface** - I believe this may no longer be needed?  It is possible to represent a separate service-side and transport-side interface as `ip-connection/port-id` and `connection/port-id` respectively.  I'm back-tracking also on the suggestion of a logical-interface/service-reference leaf as that requirement too may be fulfilled by the two port-ids and/or bridge-reference.

- [6] **encapsulation types** - `connection/encapsulation-type` is redundant and can be removed.

- `tagged-interface/qinany` -  I don't think this makes sense in the L3NM and should be removed?  We can't encapsulate IP traffic into this.  If there is a connection into some qinany service, then qinq or dot1q tagging would be needed for siphoning a given cvlan-id or native customer traffic into the `vpn-network-access/ip-connection`.

## Updated connection/ip-connection subtrees

```
             ...
             +--rw connection
             |  +--rw port-id?              vpn-common:vpn-id
             |  +--rw bridge-reference?     vpn-common:vpn-id
             |  +--rw encapsulation
             |  |  +--rw type?                identityref
             |  |  +--rw dot1q        {vpn-common:dot1q}?
             |  |  |  +--rw tag-type?   identityref
             |  |  |  +--rw cvlan-id?   uint16
             |  |  +--rw qinq {vpn-common:qinq}?
             |  |  |  +--rw tag-type?   identityref
             |  |  |  +--rw svlan-id    uint16
             |  |  |  +--rw cvlan-id    uint16
             |  |  +--rw priority
             |  |  |  +--rw tag-type?   identityref
             |  +--rw transport
             |  |  +--rw transport-type?     identityref
             |  |  +--rw pseudowire
             |  |  |  +--rw vcid?      uint32
             |  |  |  +--rw far-end?   union
             |  |  +--rw vpls
             |  |  |  +--rw vcid?      union
             |  |  |  +--rw far-end?   union
             |  |  +--rw vxlan {vpn-common:vxlan}?
             |  |     +--rw vni-id       uint32
             |  |     +--rw peer-mode?   identityref
             |  |     +--rw peer-list* [peer-ip]
             |  |        +--rw peer-ip    inet:ip-address
             |  +--rw bearer
             |     +--rw bearer-reference?   string
             |            {vpn-common:bearer-reference}?
             :
             +--rw ip-connection
             |  +--rw port-id?              vpn-common:vpn-id
             .. ...
```

## Examples

Example for L3 service termination on Q-in-VNI L3 gateway

```
vpn-network-access L3ACCESS_VNI_1001_10
  connection
    port-id lt-0/0/0.50
    bridge-reference VNI_1001
    encapsulation
      type dot1q
      qinq
        vlan-id 10
    transport
      vxlan
        vni 1001
  ip-connection
    port-id lt-0/0/0.51
```

Example for L3 service termination on a pseudowire service interface

```
vpn-network-access L3ACCESS_PW_10_100
  connection
    port-id pw10.0
    transport
      pseudowire
        vcid 100
        far-end 198.51.100.10
  ip-connection
    port-id pw10.100
```

Example for L3 service termination natively into a counterpart L2 vpn-node instance

```
vpn-network-access L3ACCESS_L2VPN_100
  connection
    l2vpn-id L2VPN_100
    bridge-reference L2VPN_100
  ip-connection
    port-id irb.100
```

Example for L3 service termination on a MEF EFP, via a local bridge domain.

```
vpn-network-access L3ACCESS_1003_10
  connection
    port-id Te0/0/1.10
    bridge-reference 101
    encapsulation
      type dot1q
        vlan-id 10
  ip-connection
    port-id BDI101
```

Example for logical L3 interface with native L2 tagging/classification

```
vpn-network-access L3ACCESS_1004_120
  connection
    port-id xe-0/0/0.201
    encapsulation
      type qinq
      qinq
        svlan-id 120
        cvlan-id 10
```

**Comment by sbarguil** [comment]
I have created a PR to see how this proposal can be addressed in the model. I agree in some on the changes to clarify the  structure and avoid duplications. Please see #281 to validate the changes 

Two of the things that I have not included and that we can discuss futher are:
- Port-id replicated in `connection` and `ip-connection`. 
- Bridge Domain in the `connection`container.

**Comment by oscargdd** [comment]
-> Agree on changing from tagged-interface to encapsulation. 
--> I agree decoupling the vxlan from encapsulation. In essence, the use case is that the CE-PE connection is a vxlan tunnel (identified by a VNI) and the traffic can come tagged or untagged.
--> Agree on creating a container to put together the different configurations for the cases where the vpn_network_access is not based on a physical interface, but on a "logical" one. "Transport"(as proposed by Paul might be confusing with the underlay-transport. Also, I agree with Med's comment on Samier's PR that remote-end-points might be also confusing.

Let us work first on a definition of the containter and then derive the name :-) For me, the X cointainer is used when the L2 termination of the CE-PE connection is NOT a phyisical interface (it is a pseudowire, a VXLAN tunnel or a VPLS termination).....

Do we need a "type" to indicate the type of connection or just with the presence of the relevant configuration is OK?

Maybe (unless you see it really redundant) we could say connection-type: VXLAN, PW, VPLS, NATIVE ... 

@p-sherratt What is the motivation of having different port-id for the L2 termination and the IP configuration? 

Do we really need to model the bridge domain here?

**Comment by p-sherratt** [comment]
> Agree on creating a container to put together the different configurations for the cases where the vpn_network_access is not based on a physical interface, but on a "logical" one

I would shy away from driving any part of the current model based on "physical" or "logical" interfaces, because:

1. There are no details in the current L3NM specific to "physical" interface types - nothing describing LACP, CFM, etc. 
2. For L3 perspective the language needs to be more precise - the difference between physical and logical interface from L3 perspective is very woolly and device-specific.  It is common that services can be terminated on a logical interface as a direct child of a physical interface or bridge domain.
3. The only true "physical" L3 interface would be an untagged access interface but there's no need to differentiate on this being physical vs logical, as we simply wouldn't be adding any `connection `or `connection/transport` details to this.  It would be referenced only at the `l3-connection/port-id` level.

It may be worth revising the `vpn-network-access-type` options too?  for example:
- ethernet-access  -- is point-to-point/multipoint relevant in L3NM ?
- subscriber-access
- overlay-network-access
- loopback
- any others?


> What is the motivation of having different port-id for the L2 termination and the IP configuration?

I think a third port-id may be beneficial too for transport/overlay network connection.

The port references used for implementing a specific service are important for:

- correlating service-specific telemetry received from the network,
- identifying the specific interface on which L2 encapsulation is to be configured,
- identifying the specific interface on which L3 termination is to be configured,
- identifying the interface on which an overlay network endpoint or pseudowire is built.

Depending on the implemented interface type(s), the same port-id value may also appear in multiple containers, for example:

- multi-layer interface (ip-connection, connection)
- layer-2 tunnel interface (connection, transport)
- layer-3 tunnel interface (ip-connection, transport)


>  "Transport"(as proposed by Paul might be confusing with the underlay-transport. Also, I agree with Med's comment on Samier's PR that remote-end-points might be also confusing.
> Let us work first on a definition of the containter and then derive the name :-)

This container is decribing an overlay network onto which we are providing a layer-3 gateway into the layer-3 vpn-service. 

I'm not sure myself if "transport" is the best name.  Maybe something like "overlay-connection", and move it up a level?  then there's no need for the separate `connection/encapsulation` container either and encapsulation details can remain directly under `connection` (with "untagged" remaining as one of the encapsulation-types).


> Do we need a "type" to indicate the type of connection or just with the presence of the relevant configuration is OK?

In the proposed structure the "connection" container represents all lower-layer encapsulation and/or overlay network transport details.  It makes no assumptions about the interface type referenced by connection/port-id except that it should be the interface used for L2 encapsulation/segmentation, so there's not really any value in adding a connection-type here and may even detract from usability in that it prescribes implementation-specific details.

Just the vpn-network-access-type would do IMO -- adding connection-type is redundant information.


> Do we really need to model the bridge domain here?

I feel the provision of this bridge-reference and also the other `port-id` leafs supersedes the `connection/bearer/local-reference` and is clearer for coordination of the network.

A bridge domain is important especially for configuring a multi-point L3 gateway for a L2VPN service natively (rather than an access pseudowire into another L2VPN vpn-node).

Other instances where a bridge domain is needed may be implementation-specific, but still worth including nonetheless as we are already representing a port-id, and a simple bridge reference is of similar level of detail and would likely be assigned at the same time as the port-id(s).



## Updated subtrees, taking into account these comments:
```
             ...
   *         +--rw vpn-network-access-type?    identityref
             +--rw connection
             |  +--rw port-id?              vpn-common:vpn-id
   *         |  +--rw bridge-reference?     vpn-common:vpn-id
             |  +--rw bearer
             |  |  +--rw bearer-reference?   string
             |  |         {vpn-common:bearer-reference}?
   *         |  |                    # (removed local-reference)
             |  +--rw encapsulation-type?    identityref
             |  +--rw dot1q        {vpn-common:dot1q}?
             |  |  +--rw tag-type?   identityref
   *         |  |  +--rw cvlan-id    uint16     # changed: should be mandatory
             |  +--rw qinq {vpn-common:qinq}?
             |  |  +--rw tag-type?   identityref
             |  |  +--rw svlan-id    uint16
             |  |  +--rw cvlan-id    uint16
             |  +--rw priority
             |     +--rw tag-type?   identityref
   *         +--rw overlay-connection
   *         |  +--rw port-id?              vpn-common:vpn-id
   *         |  +--rw l2vpn-id?             vpn-common:vpn-id
   *         |  +--rw overlay-type?     identityref
             |  +--rw pseudowire
             |  |  +--rw vcid?      uint32
             |  |  +--rw far-end?   union
             |  +--rw vpls
             |  |  +--rw vcid?      union
             |  |  +--rw far-end?   union
             |  +--rw vxlan {vpn-common:vxlan}?
             |     +--rw vni-id       uint32
             |     +--rw peer-mode?   identityref
             |     +--rw peer-list* [peer-ip]
             |        +--rw peer-ip    inet:ip-address
             +--rw ip-connection
   *         |  +--rw port-id?              vpn-common:vpn-id
             .. ...
```

**Comment by boucadair** [comment]
Thank you all for sharing your thoughts and inputs. I like much where we ended with the connection container.

**Comment by p-sherratt** [comment]
Looks great!   Last few points from reviewing the latest changes...

```
                       |  +--rw l2-tunnel-service   <-- not just point-to-point tunnels.  maybe `l2-transport-service` is better?
                       |  |  +--rw type?         identityref
                       |  |  +--rw pseudowire
                       |  |  |  +--rw vcid?      uint32
                       |  |  |  +--rw far-end?   union
                       |  |  +--rw vpls
                       |  |  |  +--rw vcid?      union
                       |  |  |  +--rw far-end?   union   <-- this should be a list of VPLS nodes if not auto-discovered through signalling
                       |  |  +--rw vxlan {vpn-common:vxlan}?
                       |  |     +--rw vni-id             uint32
                       |  |     +--rw peer-mode?         identityref
                       |  |     +--rw peer-ip-address*   inet:ip-address  <-- this should be a list if using static ingress replication
```

- It might also include L2TP?

- There may be other L2 and also L3 transport types too - multipoint GRE, DMVPN, SD-WAN flavour XYZ but probably better these are implemented as vendor augmentations if needed?

**Comment by boucadair** [comment]
On the tunnel vs transport terminology, I'm trying to avoid the use of "transport" as this will be a source of noise from "transport" (layer 4) reviewers as the document will now enter the IETF Last call review. 

For the other points, we don't need to be exhaustive and can be implemented as vendor augmented when needed.

**Comment by boucadair** [comment]
Agree that it is cleaner to have a choice for l2vpn-id and l2-tunnel-service. Fixed in https://github.com/IETF-OPSAWG-WG/lxnm/commit/7b8917bcae923970b2835d3838b4ea70a4c2604c.
