### ISSUE TITLE
Check Signaling Options model structure and ailing the services types

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#282]

**Comment by boucadair** [comment]
We have this included in the draft: 

```
                  +--------------+---------------------+
                  | Service Type | Signaling Options   |
                  +--------------+---------------------+
                  | vpls         | t-ldp-pwe, l2tp-pwe |
                  | vpws-evpn    | evpn-bgp            |
                  | pbb-evpn     | evpn-bgp            |
                  | mpls-evpn    | l2vpn-bgp, evpn-bgp |
                  | vxlan-evpn   | evpn-bgp            |
                  +--------------+---------------------+
```

**Comment by sbarguil** [comment]
The new service type has been added in 90fb1d1a1fc6cccd2159a6880bfecf55c65d1aa4

| Service Type   | Signaling Options              |
|----------------|--------------------------------|
| vpws           | t-ldp-pwe                      |
| vpls           | t-ldp-pwe, l2tp-pwe, l2vpn-bgp |
| vpws-evpn      | evpn-bgp                       |
| pbb-evpn       | evpn-bgp                       |
| mpls-evpn      | evpn-bgp                       |
| vxlan-evpn     | evpn-bgp                       |
| E-tree         | TBD                            |
| Multicast EVPN | TBD                            |
