### ISSUE TITLE
Quision regarding service topology

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/lxnm#293]
Question...
with respect to  vpn-service-topology vpn-targets per node.
what if the user send (for example) any2any topology and vpn-targets that are not align with this topology, what should the server do in such a case?

**Comment by boucadair** [comment]
Hi Erez, this inconsistency (and others) should be handled by the implementation. 

That's said, it would be better if we have some guards in the model. Do you have in mind some checks that we may add? Thanks.
