### ISSUE TITLE
route-targets 

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/lxnm#301]
The current vpn-targets if a a list of containers , one container is {id, list of route-targets, type } so the user can create upto 256 vpn-target containers , and route-target may be repeated 

          +-- vpn-target* [id]
            |  +-- id?                  int8
            |  +-- route-targets* [route-target]
            |  |  +-- route-target?   rt-types:route-target
            |  +-- route-target-type    rt-types:route-target-type

I believe that the id had no added value and the container may be implemented as follows

                   +--rw vpn-targets
                    |  |  +--rw route-targets* [route-target]
                    |  |     +--rw route-target    rt-types:route-target
                    |  |     +--rw route-target-type rt-types:route-target-type

so the same rout-target will no appear in several times:

list route-targets {
        key "route-target";
        description
          "List of RTs. and types";
        leaf route-target {
          type rt-types:route-target;
          description
            "Conveys an RT value.";
        }
	leaf route-target-type {
           type rt-types:route-target-type;
	   mandatory true;
           Description
               "Import/export type of the RT.";
      }

**Comment by sbarguil** [comment]
IMO this structure allows the creation of boolean (AND, OR) operations between the route-targets, for example:

- Import the targets  that match the following communities: (6500:1 **or** 6500:2) **and** (6500:3).

![image](https://user-images.githubusercontent.com/13772485/120615503-a2a7bc80-c458-11eb-835c-ffa95be438c7.png)

If we don't keep the ID just one operation can be allowed. 

What do you think? We can also add a parameter to capture this boolean option? or keep it is a defined now.

**Comment by boucadair** [comment]
> What do you think? We can also add a parameter to capture this boolean option? or keep it is a defined now.

I tend to keep it as it is but consider adding some clarification text to the common module to explain some "potential usage" that is mead possible with the "id".

**Comment by segevere** [comment]
I cant understand how the ID helps , in the end of the day it is a finite list of export only RTs , import only RTs and both RTs.

**Comment by sbarguil** [comment]
The ID allows to separate the Targets that can operated as an OR (under the same ID) of the ones to operate as an AND (different IDs).

**Comment by sbarguil** [comment]
Agree to include in the common module the sentence to explain the usage.
