### ISSUE TITLE
Restructure connection container in L2NM (similar work as in L3NM)

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/lxnm#302]
The L2NM connection container needs to be restructured. 

The "physical-interface" container has information about the speed port, etc. The impression is that the configuration of the physical interface impacts different services. Hence, L2NM might not be the best place to manage the phisycal interface. It is included as it was defined in L2SM

L2SM defined:
```
5.3.2.2.1.  Untagged Interface

   For each untagged interface (untagged-interface), there are basic
   configuration parameters like interface index and speed, interface
   MTU, auto-negotiation and flow-control settings, etc.  In addition,
   and based on mutual agreement, the customer and provider may decide
   to enable advanced features, such as LLDP, IEEE 802.3ah
   [IEEE-802-3ah], or MAC loop detection/prevention at a UNI.  If loop
   avoidance is required, the attribute "uni-loop-prevention" must be
   set to "true".
```
The advance features shown in L2SM are applicable to both tagged and untagged interfaces, so in L2NM, they can be handled separately. 

We believe the configuration of physical parameters belongs to the interface model and its an action to do in the network creation phase.

**Comment by sbarguil** [comment]
The latest version of the current proposal:

![image](https://user-images.githubusercontent.com/13772485/121529084-58947d00-c9fc-11eb-95c4-46946d125a00.png)

**Comment by sbarguil** [comment]
Regarding the previous meeting action point, the IEEE 802.3ah are dependent of the Physical Media : 

````
The IEEE 802.3ah standard for Operation, Administration, and Management (OAM) provides a specification for Ethernet in the first mile (EFM) connectivity. EFM defines how Ethernet can be transmitted over new media types using new Ethernet physical layer (PHY) interfaces. You can configure IEEE 802.3ah OAM on Ethernet point-to-point direct links or links across Ethernet repeaters. 
````

IMHO it can be removed from the final structure.

**Comment by boucadair** [comment]
Thanks, Samier. 

I suggest that we add some text to the I-D to basically state that phy-specific can be handled by device modules + removed it as the same port may be shared between services (tweaking it at the level of a specific service may have implications on other services).
