### ISSUE TITLE
PE-PE Autodiscovery

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#304]
for the tunnels creations the ip address of the other PE can be auto-discovered and not required to be direclty configured on the model. 

The current solution just allows the ip address configuration on the following leafs:

 |     |  +--rw ac-pw-list* [peer-addr vc-id]                
 |     |  |  +--**rw peer-addr      inet:ip-address**                
 |     |  |  +--rw vc-id          vpn-common:vpn-id

It is necessary to explore the possibility to handle the auto-discovery case, to provide more flexibility and expand usability of the model.

**Comment by boucadair** [comment]
I think we need to go through https://datatracker.ietf.org/doc/html/rfc6074 to make sure key variants are covered by the model. For example, check how/whether to map to VSI-ID, VPLS-id, etc.

**Comment by boucadair** [comment]
@sbarguil, I made changes to the LDP part, but I'm still not happy with it as there are nodes that are shared with the l2tp case (agi, taii).

**Comment by boucadair** [comment]
Updates at 5aa7289
