### ISSUE TITLE
RT Auto-derivation in the L2nm

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#305]
> **Route Targets**

The EVPN route MAY carry one or more Route Target (RT) attributes. RTs may be configured (as in IP VPNs) or may be derived automatically.

If a PE uses RT Constraint, the PE advertises all such RTs using RT Constraints per [RFC4684].  The use of RT Constraints allows each EVPN route to reach only those PEs that are configured to import at least one RT from the set of RTs carried in the EVPN route.

> **Auto-derivation from the Ethernet Tag ID**

   For the "Unique VLAN EVPN" scenario, it is highly desirable to auto-derive the RT from the Ethernet Tag ID (VLAN ID) for that EVPN instance.  The procedure for performing such auto-derivation is as follows:

 - The Global Administrator field of the RT MUST be set to the Autonomous System (AS) number with which the PE is associated.
- The 12-bit VLAN ID MUST be encoded in the lowest 12 bits of the Local Administrator field, with the remaining bits set to zero.

**Comment by boucadair** [comment]
It seems that it was closed as on of the PRs covers many edits.

**Comment by boucadair** [comment]
@sbarguil : I removed the augment thing and went with an explicit control leaf to indicate whether auto-derivation is used for the EVPN case.
