### ISSUE TITLE
Add SIMPLE understandable examples in L2NM draft

### ISSUE THREAD

**Issue by oscargdd** [IETF-OPSAWG-WG/lxnm#313]
In order to show readers how the model is used to describe a L2VPN, we need to add examples of:

* VPLS
* Simple EVPN (at least one flavour)
* Signaling & discovery done by BGP
* Onther case mixing BPG and T-LDPS

* We can try to reuse the network topology exisiting in Figure 1: Example Network Topology from RFC6624 

[[Med: We used to have this separate issue, merging here to track one single issue:

```
In the last OPSAWG meeting there ware the following comments can hierarchical
VPN be supported in this SM? Oscar: Yes, but more review is needed to see if it
is fully supportable Zhenbin Li: Inter-AS scenario?

The proposal is to add examples in the draft to explain the usage in both scenarios.
```

**Comment by lmunozm** [comment]
As a suggestion, EVPN case example can have a reference to the Figure 1 in RFC8388 Usage and Applicability of BGP MPLS-Based Ethernet VPN. The graph shows the main feature additions of EVPN (topology with dual homed CE).

**Comment by boucadair** [comment]
We have a fair number of examples.
