### ISSUE TITLE
Active Global Parameters Profiles relation with Global Parameters Profiles 

### ISSUE THREAD

**Issue by vlopezalvarez** [IETF-OPSAWG-WG/lxnm#324]
I think that the relation between Active Global Parameters Profiles relation with Global Parameters Profiles is not very clear in the text. I thought that Active Global Parameters Profiles are some used Global Parameters Profiles and I was expected a string with the profile id. However, as there are the parameters for the Global Parameters Profile, it looks like they can be configured directly in the Active Global Parameters Profile without a pre-configuration in the Global Parameters Profiles list. 

Which should be the behaviour in this case? Should the SDN controller create a Global Parameters Profile in the list?

We can include some text to clarify this.

**Comment by boucadair** [comment]
Hi @vlopezalvarez, 

The intent is to allow overriding some values at the VPN node level (MTU, for example). Values defined at the VPN node level take precedence over the global ones defined at the service level.

**Comment by boucadair** [comment]
The same clarification applies for some nodes (mac policies) that we can tweak be at the vpn-network-access. If such values are provided, they take precedence over other (if a global profile is defined).

**Comment by vlopezalvarez** [comment]
Great... Let's keep the issue open and we include the text

Another point related. vpn-instance-profile is used in L3NM, should not we have the same naming in L2NM? I mean if the aim of the parameter is the same, it would be easier to have the same naming for both models.

**Comment by boucadair** [comment]
> Another point related. vpn-instance-profile is used in L3NM, should not we have the same naming in L2NM?

We don't use the same naming as we don't have key data nodes for a VPN instance (role, in particular).

**Comment by boucadair** [comment]
> Great... Let's keep the issue open and we include the text

We do already have text in the draft: "Values defined in 'active-global-parameters-profiles' overrides the ones defined in the VPN service level."
