### ISSUE TITLE
The LAG Interface is a standalone object

### ISSUE THREAD

**Issue by MotiMorg** [IETF-OPSAWG-WG/lxnm#328]
A Link Aggregation Group (LAG) combines multiple parallel physical connections/links existing between the CE and a Network provider's Node to form a logical connection between them. The LAG may be used for increasing the throughput between the CE and the Node (e.g., for load balancing) and/or for protecting the CE<>Node connectivity. 
Anyway, **a single LAG object is supposed to be used for multiple L2VPN and L3VPN services in parallel**. So, it should not be created in context of a single specific VPN service. Instead, it should be treated as a standalone object that one or more services may utilize simultaneously. 
Once the LAG object is configured and when the customer requests a L2VPN/L3VPN service to be provided to its CE over the LAG object, then a Connection is added to that VPN service and it simply refers to the LAG object. The only VPN-specific detail to provide is the unique VLAN ID (i.e., among the 4K available for that LAG) allocated for the specific VPN's traffic over the LAG, so the traffic will be identified on both ends of the LAG. It is exactly same as allocating a VLAN ID as part of creating a L2/L3 LIF over a physical port.

**Comment by boucadair** [comment]
Hi Moti, 

The initial intent for the current design is to ease the mapping with the service request. Please see https://datatracker.ietf.org/doc/html/rfc8466#section-5.3.2.2.3. 

Some these data nodes have to be managed per service.

**Comment by oscargdd** [comment]
Agree to maintain current structure, but add explanatory text in the draft about ensuring the consistency of the LAG configuration. See for example, the section about ESI autoderivation based on LACP.
