### ISSUE TITLE
VPN PM: The string type definition of “pm-source” needs to be considered - from IETF 111 presentation

### ISSUE THREAD

**Issue by lana-wu** [IETF-OPSAWG-WG/lxnm#332]
Revision 01: https://datatracker.ietf.org/doc/draft-ietf-opsawg-yang-vpn-service-pm/ 
OPSAWG meeting discussion：
     augment /nw:networks/nw:network/nt:link:
       +--rw pm-attributes
          +--rw low-percentile?         percentile
          +--rw middle-percentile?      percentile
          +--rw high-percentile?        percentile
          **+--ro pm-source?              string**
From chair Joe: pm-source is a string. Would an identity be better?
Robert Wilton: if there are potentially multiple sources then maybe a leaflist or identities would also make sense

**Comment by boucadair** [comment]
The comment from Joe makes sense. This should be linked with the examples provided in the draft:

   "pm-source":  Indicates the performance monitoring source.  The data
      for the topology link can be based, e.g., on BGP-LS [RFC8571].
      The statistics of the VPN abstract links can be collected based
      upon VPN OAM mechanisms, e.g., OAM mechanisms specified in
      [I-D.ietf-opsawg-l3sm-l3nm], or Ethernet service OAM specified in
      [I-D.ietf-opsawg-l2nm].  Alternatively, the data can be based upon
      the underlay technology OAM mechanisms, for example, GRE tunnel
      OAM.

**Comment by lana-wu** [comment]
@vlopezalvarez Looking at the LxNM draft, I find OAM defined under "vpn-network-access", which is different with this issue. This issue is about the PM metric of logic links between “vpn-node”. I am wondering whether this PM mechanism between “vpn-node” is in the scope of LxNM or not?

**Comment by boucadair** [comment]
Fixed in -02
