### ISSUE TITLE
L2-NM lag-interface list

### ISSUE THREAD

**Issue by sbarguil** [IETF-OPSAWG-WG/lxnm#335]
Issue opened based on email from Julian.
I am puzzled why lag-interface container has a list of lag-interfaces. I would think an individual vpn-network-access would only ever have at most one lag-interface?

```
container lag-interface {
  if-feature "vpn-common:lag-interface";
  
  description
    "Container of LAG interface attributes
     configuration";
    
    list lag-interface {
      key "lag-interface-number";
      description
        "List of LAG interfaces";
        
        leaf lag-interface-number {
          type uint32;
          description
            "LAG interface number";
        }
    }
}
```

**Comment by julianL999** [comment]
We can remove "lag-interface-number" as well, as that was the index for each list item, and we have removed the list.
