### ISSUE TITLE
L2NM: leaf should not be called "type" as it is a Yang keyword

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/lxnm#340]
There is a leaf called "type", but "type" is a Yang keyword. It causes problems, for example it cause an error in pyang if it is part of a deviation. Also at least one Yang editor highlights the word in the colour used for Yang keywords, which is confusing.

   container signaling-option {
              description
                "Container for the L2VPN signaling.";
              leaf mtu-pw {
                type uint16;
                description
                  "Sets the PW MTU.";
              }
              leaf mtu-allow-mismatch {
                type boolean;
                description
                  "When set to true, it allows MTU mismatch.";
                reference
                  "RFC 4667: Layer 2 Virtual Private Network (L2VPN)
                             Extensions for Layer 2 Tunneling
                             Protocol (L2TP), Section 4.3";
              }
              leaf type {   <<<<<<<<<
                type leafref {
                  path "/l2vpn-ntw/vpn-services/vpn-service"
                     + "/signaling-type";
                }
                description
                  "VPN signaling type.";
              }

**Comment by boucadair** [comment]
Rename this one, but also other simialr ones for better readability.
