### ISSUE TITLE
Multiple provider IP addresses 

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/lxnm#346]
the model today gives the opportunity to set single IPv4 address and single IPv6 address as profiler address as local address (I've copy paste the IPv4 example) 
in our system the user can define up to 8 different IPv4 and 8  different IPv6 addresses on the same interface . 
suggestion - let a list of local-addresses  

                 container ipv4 {
                    if-feature "vpn-common:ipv4";
                    description
                      "IPv4-specific parameters.";
                    leaf local-address {
                      type inet:ipv4-address;
                      description
                        "The IP address used at the provider's
                         interface.";
                    }
                    leaf prefix-length {
                      type uint8 {
                        range "0..32";
                      }
                      description
                        "Subnet prefix length expressed in bits.
                         It is applied to both local and customer
                         addresses.";
                    }

**Comment by boucadair** [comment]
Hi Erez, 

I agree that more than one address can be assigned on a given interface, but the decision we made is to align with the service request (excerpt from RFC8299):

                   +--rw ip-connection
                   |  +--rw ipv4 {ipv4}?
                   |  |  +--rw address-allocation-type?   identityref
                   |  |  +--rw provider-dhcp
                   |  |  |  +--rw provider-address?
                   |  |  |  |       inet:ipv4-address
                   |  |  |  +--rw prefix-length?               uint8

Thank you.

**Comment by segevere** [comment]
Hi, 

No sure I understand how do I declare an address to be primary in RFC8299 and set anycast flag to IPv6 address.

in addition when performing the translation to L3NM there should be a room for multiple provider address , isnt it?

Thanks,
Erez
