### ISSUE TITLE
vpn-common: "status" causes problems, as it is a Yang keyword

### ISSUE THREAD

**Issue by julianL999** [IETF-OPSAWG-WG/lxnm#347]
vpn-common has leaf and containers called "status". However "status" is a Yang keyword. This causes problems as it prevents modification using deviations (when using pyang). Also colour-coded yang editors highlight the word in the colour used for yang keywords.

**Comment by boucadair** [comment]
Hi Julian,

I'm not aware of any normative text that prevents the use of such names. For example, the following widely implemented YANG modules uses YANG keywords as name:
* RFC8343: type leaf
* RFC8344: status leaf
