### ISSUE TITLE
Preference-based DF selection 

### ISSUE THREAD

**Issue by MotiMorg** [IETF-OPSAWG-WG/lxnm#351]
The 'preference' parameter, currently located in df-election container, is "the PE preference to become the DF in the ES". 
If that so, then the parameter must be specified per PE (actually, per PE per service) rather than as a single value on the whole ES level.
So, I recommend on moving the parameter next to ethernet-segment-identifier (in the group list). The parameter should still be conditionally relevant, i.e, only when the group is an ES instance and only when the df-election-method of that ES is 'preference' (preference-based).

**Comment by boucadair** [comment]
Hi Moti, 

Good catch. Please check the proposed PR to fix this. Thank you.
