### ISSUE TITLE
change ECI to Ribbon

### ISSUE THREAD

**Issue by segevere** [IETF-OPSAWG-WG/lxnm#355]
Can my email change in l3nm to my new ribbon's   email to erez.segev@rbbn.com (instead of ECI).
Also in B.4 section change the company name from Ribbon-ECI (B.4) and ECI Telecom (Contributors) to be Ribbon Communications.

Thanks
Erez

**Comment by boucadair** [comment]
Hi Erez,

Noted. We don't have the control on the document at this stage as it is still with the [RFC Editor](https://www.rfc-editor.org/current_queue.php#draft-ietf-opsawg-l3sm-l3nm).

We will make these changes in AUTH48 when we receive the edited version from the RFC editor. We expect that to happen in the coming few weeks.

**Comment by boucadair** [comment]
The request was made to the RFC Editor
