### ISSUE TITLE
Benoit's comments

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/lxnm#358]
Out of the two use cases (I mentioned in my email below)
1. Do we want to say that there are existing SAPs on PE routers, to which we can deploy new services?
2. Or do we want to say there is an existing service that connects CE2 to a specific SAP on PE2?
I have a direct need for 2

**Comment by vlopezalvarez** [comment]
We will improve the text and make a proposal to Benoit

**Comment by boucadair** [comment]
Text to clarify the intended behavior was included in the candidate -01.
