### ISSUE TITLE
Type of "interface-type"

### ISSUE THREAD

**Issue by boucadair** [IETF-OPSAWG-WG/lxnm#368]
We do currently have: 

```
      leaf interface-type {
        type identityref {
          base if:interface-type;
        }
        config false;
        description
          "The type of the interface.";
      }
```

I wonder whether at the network level we simply need to refer to abstract types, e.g.,: "physical-port", "logical-subinterface", "loopback", etc.  

The exact nature of the interface (if:interface-type) can be used by querying the device can be retrieve by querying the node's interfaces.

**Comment by segevere** [comment]
interfaces can be 
- PHY - Physical port  - and can be channelized or unchanneled 
- LAG - which aggregate several PHY
- LIF - logical interface  which is a service termination point 
- LB - loopback 
- IRB or PHT which are virtual defined over a device but not part of inventory 
not real device interface 
going to L2VPN
- UNI
- NNI
- etc.

**Comment by boucadair** [comment]
Thanks, Erez. I like that extended list. 

For UNI/NNI, I think this is orthogonal to the other types. We may consider having a node to capture separately whether a SAP is UNI or NNI.

**Comment by segevere** [comment]
agree, UNI NNI just implies on the role of the port in the network

**Comment by boucadair** [comment]
Thanks, Erez. 

For now, went for the following in #372 : 

```

  identity interface-type {
    description
      "Base identity for the interface type.";
  }

  identity phy {
    base interface-type;
    description
      "Phyical port.";
  }

  identity loopback {
    base interface-type;
    description
      "Loopback interface.";
  }

  identity lag {
    base interface-type;
    description
      "LAG interface.";
  }

  identity irb {
    base interface-type;
    description
      "Integrated Routing Bridge (IRB).";
  }

  identity local-bridge {
    base interface-type;
    description
      "A local bridge reference to accommodate, e.g., 
       implementations that require internal bridging.
       When such a type is used, a reference to a local
       bridge domain is used to identify the interface.";
  }

  identity logical {
    base interface-type;
    description
      "Refers to a logical sub-intreface that is typically 
       used to bind a service. This type is used only
       if none of the other logical types can be used.";
  }
```
